spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}.postgres.database.azure.com:${POSTGRES_PORT}/${POSTGRES_DATABASE}?useSSL=true&requireSSL=FALSE
    username: ${POSTGRES_USER}@${POSTGRES_HOST}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties: 
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
